<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3MGTiax\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3MGTiax/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3MGTiax.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3MGTiax\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3MGTiax\App_KernelDevDebugContainer([
    'container.build_hash' => '3MGTiax',
    'container.build_id' => '36d41535',
    'container.build_time' => 1588671884,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3MGTiax');
