<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOpuDMoH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOpuDMoH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOpuDMoH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOpuDMoH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOpuDMoH\App_KernelDevDebugContainer([
    'container.build_hash' => 'OpuDMoH',
    'container.build_id' => 'a7331314',
    'container.build_time' => 1588758984,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOpuDMoH');
